# .github/workflows/deploy.yml
name: Deploy to Lightsail (info@shipsar.in)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSHELL_SSH_KEY }}" > ~/.ssh/lightshell_key
          chmod 600 ~/.ssh/lightshell_key
          ssh-keygen -y -f ~/.ssh/lightshell_key > ~/.ssh/lightshell_key.pub
          echo "Host my-lightshell-instance
          HostName 3.111.126.28
          User ubuntu
          IdentityFile ~/.ssh/lightshell_key" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Start SSH Agent and Add Key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/lightshell_key

      - name: SSH into Lightsail and deploy
        run: |
          ssh -t -o StrictHostKeyChecking=no my-lightshell-instance << 'EOF'
            set -e  # Exit immediately on error
            cd /home/ubuntu/projects/M-PTravels

            # Ensure we have the latest code
            git fetch origin main
            if ! git diff --quiet HEAD origin/main; then
              git reset --hard origin/main
              git pull origin main
            else
              echo "No changes detected."
            fi

            cd backend
            source ~/.bashrc 
            # Ensure dependencies are installed
            npm install --production

            # Restart PM2 process safely
            if pm2 describe mp-backend > /dev/null; then
              pm2 restart mp-backend
            else
              pm2 start npm --name mp-backend -- run start
            fi
          EOF
