# .github/workflows/deploy.yml
name: Deploy to Lightsail (info@shipsar.in)

on:
  push:
    branches:
      - main

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSHELL_SSH_KEY }}" > ~/.ssh/lightshell_key
          chmod 600 ~/.ssh/lightshell_key

      - name: Add SSH Host Key
        run: |
          ssh-keyscan -H 3.111.126.28 >> ~/.ssh/known_hosts

  checkout-code:
    needs: setup-ssh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code on Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/lightshell_key ubuntu@3.111.126.28 << 'EOF'
            set -e
            cd /home/ubuntu/projects/M-PTravels
            git fetch origin main
            if ! git diff --quiet HEAD origin/main; then
              git reset --hard origin/main
              git pull origin main
            else
              echo "No changes detected."
            fi
          EOF

  setup-install:
    needs: checkout-code
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js & Bun on Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/lightshell_key ubuntu@3.111.126.28 << 'EOF'
            set -e
            cd /home/ubuntu/projects/M-PTravels/backend
            whoami
            if ! command -v bun &> /dev/null
            then
                echo "bun not found, installing..."
                sudo apt update
                curl -fsSL https://bun.sh/install | bash
            fi
          EOF

      - name: Install Dependencies on Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/lightshell_key ubuntu@3.111.126.28 << 'EOF'
            set -e
            cd /home/ubuntu/projects/M-PTravels/backend
            bun install --production
          EOF

  deploy-restart:
    needs: setup-install
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PM2 is Installed & Restart Service
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/lightshell_key ubuntu@3.111.126.28 << 'EOF'
            set -e
            cd /home/ubuntu/projects/M-PTravels/backend
            export PATH=$PATH:/home/ubuntu/.bun/bin
            source ~/.bashrc

            if ! command -v pm2 &> /dev/null
            then
                echo "pm2 not found, installing pm2..."
                bun add pm2
            fi

            if pm2 describe mp-backend > /dev/null; then
              pm2 restart mp-backend
            else
              pm2 start npm --name mp-backend -- run start
            fi
          EOF
