name: Deploy to Lightsail (info@shipsar.in)

on:
  push:
    branches:
      - main

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Key and Verify Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.LIGHTSHELL_SSH_KEY }}") ubuntu@3.111.126.28 "echo 'SSH Connection Successful!'"

  checkout-code:
    needs: setup-ssh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Code on Server
        run: |
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.LIGHTSHELL_SSH_KEY }}") ubuntu@3.111.126.28 << 'EOF'
            set -e
            cd /home/ubuntu/projects/M-PTravels
            git fetch origin main
            if ! git diff --quiet HEAD origin/main; then
              git reset --hard origin/main
              git pull origin main
            else
              echo "No changes detected."
            fi
          EOF

  setup-dependencies:
    needs: checkout-code
    runs-on: ubuntu-latest
    steps:
      - name: Install Bun and Dependencies
        run: |
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.LIGHTSHELL_SSH_KEY }}") ubuntu@3.111.126.28 << 'EOF'
            set -e
            cd /home/ubuntu/projects/M-PTravels/backend
            whoami
            if ! command -v bun &> /dev/null
            then
                echo "bun not found, installing..."
                sudo apt update
                curl -fsSL https://bun.sh/install | bash
            fi
            bun install --production
          EOF

  deploy-application:
    needs: setup-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PM2 is Installed & Restart Application
        run: |
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.LIGHTSHELL_SSH_KEY }}") ubuntu@3.111.126.28 << 'EOF'
            set -e
            cd /home/ubuntu/projects/M-PTravels/backend
            export PATH=$PATH:/home/ubuntu/.bun/bin
            source ~/.bashrc

            if ! command -v pm2 &> /dev/null
            then
                echo "pm2 not found, installing pm2..."
                bun add pm2
            fi

            if pm2 describe mp-backend > /dev/null; then
              pm2 restart mp-backend
            else
              pm2 start npm --name mp-backend -- run start
            fi
          EOF
